== Project Management

=== Übergeordnetes Ziel & Aufgaben
Das übergeordnete Ziel im Bereich des Projektmanagements bestand darin, eine funktionierende organisatorische Struktur für das Projektteam zu schaffen, um eine effektive Zusammenarbeit zu ermöglichen. Zu Beginn herrschte eine unstrukturierte Ausgangslage ohne definierte Rollen, Verantwortlichkeiten oder klar etablierte Prozesse. Daraus ergab sich die Notwendigkeit, ein gemeinsames Verständnis für Arbeitsweise und Kommunikation zu entwickeln. Die zentralen Aufgaben umfassten die Konzeption und Einführung einer geeigneten Projektstruktur, die Gliederung des Gesamtteams in kleinere Arbeitseinheiten sowie die Integration iterativer Abstimmungs- und Planungsprozesse. Ebenfalls Bestandteil war die Durchführung der regelmäßigen Sprint-Plannings, Reviews und Retrospektiven im Rahmen der wöchentlichen Projekttermine sowie die Sicherstellung des teamübergreifenden Austauschs bei zentralen Fragestellungen wie Architekturentscheidungen und inhaltlichen Abhängigkeiten.

=== Teilaufgaben
Zu den konkreten Teilaufgaben zählten die Planung und Steuerung des Projektverlaufs, die Koordination der beteiligten Teilteams, die Organisation und Moderation der Projektmeetings sowie die Strukturierung der Aufgabenverteilung. Für die operative Umsetzung wurde ein hybrider agiler Ansatz gewählt, der Elemente aus Scrum und Kanban kombinierte. Wöchentliche Sprints bildeten den Rahmen für eine zyklische Planung und Evaluation, wobei die Arbeitsstände mithilfe eines digitalen Kanban-Boards dokumentiert und nachverfolgt wurden. Dieses enthielt unter anderem die Phasen „New“, „To Specify“, „In Progress“, „To Verify“ und „Done“ und wurde sowohl zur Planung als auch zur Visualisierung des Projektfortschritts genutzt. Darüber hinaus wurde der Austausch zwischen den Teilteams durch die gemeinsame Bearbeitung und Diskussion übergreifender Themen im Rahmen der wöchentlichen Meetings sichergestellt.

=== Ergebnisse
Im Ergebnis entstand eine tragfähige Arbeitsstruktur, die auf einer Kombination aus wöchentlichen Sprintzyklen und kontinuierlicher Aufgabenverfolgung per Kanban basierte. Diese Methodik erwies sich als wirkungsvoll zur Förderung der Transparenz über den Projektstand sowie zur Unterstützung eines selbstorganisierten und zielgerichteten Arbeitsstils. Ein zentrales Ergebnis war die sukzessive Etablierung dieser Arbeitsweise über das gesamte Projekt hinweg, wodurch die Koordination innerhalb des Teams signifikant verbessert werden konnte. Zudem führten regelmäßige Retrospektiven zu einer kontinuierlichen Optimierung der Prozesse. Die schrittweise Strukturierung der Aufgaben in Form von Issues auf dem Kanban-Board ermöglichte es, eine zunehmende Übersicht über noch offene Arbeitspakete zu gewinnen und deren Bearbeitung planbar zu gestalten.

=== Probleme & Lösungen
Im Projektverlauf traten insbesondere zu Beginn Herausforderungen im Bereich der Koordination auf. So gestaltete sich die Abstimmung zu technischen Architekturentscheidungen zunächst schwierig, da Zuständigkeiten und Kommunikationswege nicht eindeutig geregelt waren. Auch die Ressourcen- und Aufgabenplanung war in frühen Phasen durch mangelnde Transparenz über Arbeitsfortschritte und -bedarfe erschwert. Zur Lösung dieser Probleme wurden verschiedene Maßnahmen ergriffen: Der regelmäßige Austausch in Form von Retrospektiven und Sprint Reviews diente der Identifikation und Diskussion bestehender Hindernisse. Darüber hinaus wurde das Kanban-Board gezielt zur Aufgabenstrukturierung genutzt, indem für alle wesentlichen Arbeitspakete zunächst grobe Issues angelegt wurden. Diese Vorgehensweise ermöglichte eine erste Einschätzung des Gesamtumfangs und diente als Grundlage für eine realistischere Planung. Mit zunehmender Projektlaufzeit und wachsender Klarheit über Aufgabeninhalte wurde dieses Verfahren effizienter und unterstützte die teamübergreifende Zusammenarbeit.

=== Annahmen & Limitierungen
Die Arbeit im Projekt war durch mehrere Rahmenbedingungen eingeschränkt. So stand lediglich ein begrenzter Zeitrahmen zur Verfügung, innerhalb dessen alle Planungs- und Abstimmungsprozesse stattfinden mussten. Zudem arbeiteten alle Beteiligten im Rahmen eines studentischen Projekts ohne feste zeitliche Ressourcen oder dedizierte Rollen. Der Austausch fand nahezu ausschließlich während der wöchentlichen Vorlesungstermine statt, was die Flexibilität bei der Durchführung zusätzlicher Abstimmungen oder Planungen einschränkte. Ein weiteres Hemmnis bestand darin, dass agile Arbeitsmethoden wie Retrospektiven oder Kanban-Boards für viele Teammitglieder Neuland darstellten. Dies führte zu einer anfangs zurückhaltenden Nutzung entsprechender Formate, deren Mehrwert sich erst im Laufe der Zeit durch wiederholte Anwendung erschloss. Trotz dieser Einschränkungen konnte durch pragmatische Lösungsansätze und konsequente Strukturierung eine funktionsfähige Projektorganisation etabliert werden, die im weiteren Verlauf zu einer routinierten und effektiven Zusammenarbeit beitrug.

