== Project Management <arbeitspaket_project_management>

=== Übergeordnetes Ziel & Aufgaben
Das übergeordnete Ziel im Bereich des Projektmanagements bestand darin, eine funktionierende organisatorische Struktur für das Projektteam zu schaffen, um eine effektive Zusammenarbeit zu ermöglichen. Zu Beginn herrschte eine unstrukturierte Ausgangslage ohne definierte Rollen, Verantwortlichkeiten oder klar etablierte Prozesse. Daraus ergab sich die Notwendigkeit, ein gemeinsames Verständnis für Arbeitsweise und Kommunikation zu entwickeln. Neben der reinen Organisation der Projektarbeit war es auch Ziel, eine gleichmäßige Sichtbarkeit und Anerkennung für alle Teammitglieder zu erreichen, sodass individuelle Leistungen fair in die Bewertung einflossen und potenzielle Alleingänge oder isolierte Arbeitsweisen vermieden wurden. 

Die zentralen Aufgaben umfassten die Konzeption und Einführung einer geeigneten Projektstruktur, die Gliederung des Gesamtteams in kleinere Arbeitseinheiten sowie die Integration iterativer Abstimmungs- und Planungsprozesse. Ein besonderer Fokus lag darauf, Entscheidungen nur im Rahmen der offiziellen wöchentlichen Projekttermine gemeinschaftlich zu treffen, um Transparenz und Nachvollziehbarkeit zu gewährleisten. Dies schloss explizit aus, dass außerhalb dieser Runden in Kleingruppen oder informellen Kanälen entscheidungsrelevante Diskussionen geführt wurden. Ebenfalls Bestandteil war die Durchführung der regelmäßigen Sprint-Plannings, Reviews und Retrospektiven sowie die Sicherstellung des teamübergreifenden Austauschs bei zentralen Fragestellungen wie Architekturentscheidungen und inhaltlichen Abhängigkeiten. Um die Einbindung aller Teammitglieder zu fördern, war es zudem wichtig, individuelle Interessen und Kompetenzen bei der Aufgabenverteilung zu berücksichtigen. 

=== Teilaufgaben
Zu den konkreten Teilaufgaben zählten die Planung und Steuerung des Projektverlaufs, die Koordination der beteiligten Teilteams, die Organisation und Moderation der Projektmeetings sowie die Strukturierung der Aufgabenverteilung. Für die operative Umsetzung wurde ein hybrider agiler Ansatz gewählt, der Elemente aus Scrum und Kanban kombinierte. Diese Wahl ergab sich vor allem daraus, dass ein klassisches Wasserfallmodell für das studentische Projekt weder realistisch noch zielführend gewesen wäre – der verfügbare Zeitrahmen war zu knapp, um eine vollständige initiale Planung abzuwarten. Stattdessen musste direkt mit der Umsetzung begonnen werden. Daher war eine iterative und inkrementelle Entwicklung im Rahmen einer agilen Arbeitsweise für das Projektteam essenziell. Wöchentliche Sprints bildeten den Rahmen für eine zyklische Planung und Evaluation, wobei die Arbeitsstände mithilfe eines digitalen Kanban-Boards dokumentiert und nachverfolgt wurden. Dieses enthielt unter anderem die Phasen „New“, „To Specify“, „In Progress“, „To Verify“ und „Done“ und wurde sowohl zur Planung als auch zur Visualisierung des Projektfortschritts genutzt. 

Zudem wurden alle identifizierten Aufgabenbereiche gemeinsam erarbeitet, zu übergeordneten Arbeitspaketen zusammengeführt und im Konsens auf die beteiligten Teams verteilt. Entscheidungsprozesse wurden anfangs durch Umfragen unterstützt, um eine gleichberechtigte Meinungsbildung zu fördern und zu vermeiden, dass dominantere Stimmen das Gesamtbild verzerren. Die Zuweisung erfolgte in Abstimmung mit persönlichen Interessen und Präferenzen der Mitglieder, um intrinsische Motivation und aktive Beteiligung zu fördern. 

Zur weiteren Verbesserung der Abstimmungsprozesse wurden in späteren Phasen GitHub Discussions eingeführt, um technische Entscheidungen und allgemeine Fragen transparent und asynchron zu dokumentieren und zu klären. Darüber hinaus wurden die Issues zunehmend einzelnen Sprints zugeordnet, um gezielter planen zu können und den Fortschritt in Form einer Roadmap über den gesamten Projektverlauf hinweg nachzuvollziehen. Eigene Boards für jedes Team erlaubten zusätzlich eine differenzierte Betrachtung der Sprintziele auf Teilteam-Ebene. 

=== Ergebnisse
Im Ergebnis entstand eine tragfähige Arbeitsstruktur, die auf einer Kombination aus wöchentlichen Sprintzyklen und kontinuierlicher Aufgabenverfolgung per Kanban basierte. Diese Methodik erwies sich als wirkungsvoll zur Förderung der Transparenz über den Projektstand sowie zur Unterstützung eines selbstorganisierten und zielgerichteten Arbeitsstils. Ein zentrales Ergebnis war die sukzessive Etablierung dieser Arbeitsweise über das gesamte Projekt hinweg, wodurch die Koordination innerhalb des Teams signifikant verbessert werden konnte. 

Durch die Integration klarer Entscheidungswege in den gemeinsamen Projektmeetings wurde ein verlässlicher Rahmen geschaffen, der Konsensbildung förderte und parallele Einzelentscheidungen verhinderte. Die regelmäßigen Retrospektiven trugen maßgeblich zur kontinuierlichen Optimierung der Prozesse bei. Anfangs noch mit bewusst einfacher Struktur („Was lief gut?“ / „Was lief schlecht?“), wurden sie später gezielt erweitert, etwa um konkrete Action Items oder die Frage „Was sollten wir heute besprechen?“. Die zentrale Zielsetzung bestand dabei stets darin, Maßnahmen zu identifizieren, die den jeweils kommenden Sprint produktiver gestalten würden als den vorherigen. 

Die schrittweise Strukturierung der Aufgaben in Form von Issues auf dem Kanban-Board ermöglichte es, eine zunehmende Übersicht über noch offene Arbeitspakete zu gewinnen und deren Bearbeitung planbar zu gestalten. Die Einführung von Sprint-Zuordnungen auf GitHub schuf zusätzliche Planungssicherheit für die verbleibenden Zeitabschnitte des Projekts. 

=== Probleme & Lösungen
Im Projektverlauf traten insbesondere zu Beginn Herausforderungen im Bereich der Koordination auf. So gestaltete sich die Abstimmung zu technischen Architekturentscheidungen zunächst schwierig, da Zuständigkeiten und Kommunikationswege nicht eindeutig geregelt waren. Auch die Ressourcen- und Aufgabenplanung war in frühen Phasen durch mangelnde Transparenz über Arbeitsfortschritte und -bedarfe erschwert. 

Zur Lösung dieser Probleme wurden verschiedene Maßnahmen ergriffen: Der regelmäßige Austausch in Form von Retrospektiven und Sprint Reviews diente der Identifikation und Diskussion bestehender Hindernisse. Darüber hinaus wurde das Kanban-Board gezielt zur Aufgabenstrukturierung genutzt, indem für alle wesentlichen Arbeitspakete zunächst grobe Issues angelegt wurden. Dieses Vorgehen erlaubte eine erste Einschätzung des Gesamtumfangs und diente als Grundlage für eine realistischere Planung. 

Zudem wurde im weiteren Verlauf eine zentrale Sprint-Roadmap aufgebaut, mit deren Hilfe alle Issues einem konkreten Sprint zugeordnet und deren zeitliche Umsetzung koordiniert werden konnte. Dies ermöglichte nicht nur eine bessere Vorausplanung, sondern auch ein transparentes Erwartungsmanagement. Die Nutzung von GitHub Discussions erwies sich ebenfalls als hilfreich, um komplexe Fragestellungen über den Vorlesungszeitraum hinaus dokumentiert und nachvollziehbar zu besprechen. 

=== Annahmen & Limitierungen
Die Arbeit im Projekt war durch mehrere Rahmenbedingungen eingeschränkt. So stand lediglich ein begrenzter Zeitrahmen zur Verfügung, innerhalb dessen alle Planungs- und Abstimmungsprozesse stattfinden mussten. Zudem arbeiteten alle Beteiligten im Rahmen eines studentischen Projekts ohne feste zeitliche Ressourcen oder dedizierte Rollen. Der Austausch fand nahezu ausschließlich während der wöchentlichen Vorlesungstermine statt, was die Flexibilität bei der Durchführung zusätzlicher Abstimmungen oder Planungen einschränkte. 

Ein weiteres Hemmnis bestand darin, dass agile Arbeitsmethoden wie Retrospektiven oder Kanban-Boards für viele Teammitglieder Neuland darstellten. Dies führte zu einer anfangs zurückhaltenden Nutzung entsprechender Formate, deren Mehrwert sich erst im Laufe der Zeit durch wiederholte Anwendung erschloss. 

Zudem erforderte die angestrebte Gleichverteilung von Verantwortung und Anerkennung innerhalb des Teams ein hohes Maß an Abstimmung und gegenseitiger Rücksichtnahme, das über klassische Aufgabenverteilung hinausging. Entscheidungen mussten bewusst so getroffen werden, dass sie im Konsens erfolgten und nicht durch informelle Dynamiken oder dominante Einzelmeinungen geprägt wurden. Trotz dieser Einschränkungen konnte durch pragmatische Lösungsansätze, iterative Prozessoptimierung und konsequente Strukturierung eine funktionsfähige Projektorganisation etabliert werden, die im weiteren Verlauf zu einer routinierten und effektiven Zusammenarbeit beitrug. 

