services:
  blockchain-nginx:
    restart: unless-stopped
    stop_signal: SIGKILL
    networks: [net-iam]
    ports:
      - "127.0.0.1:8443:80"
    volumes:
      - ./blockchain/build/nginx/blockchain.conf:/etc/nginx/conf.d/default.conf:ro
    build:
      dockerfile: ./blockchain/build/dockerfiles/nginx.Dockerfile

  blockchain-api:
    build:
      dockerfile: ./blockchain/build/dockerfiles/blockchain-api.Dockerfile
    restart: unless-stopped
    networks: [net-iam]
    volumes:
      - ./blockchain/:/app/

  cloud-api-service:
    restart: unless-stopped
    networks: [net-iam]
    depends_on:
      - blockchain-api
      - blockchain-nginx
    build:
      context: ./cloud/
      dockerfile: ./build/Dockerfile-api
    ports:
      - "8000:8000"
    env_file: ./cloud/.env
    environment:
      BLOCKCHAIN_URL: "http://blockchain-nginx"
      DOCKER_SETUP: "true"
      TESTKEYS_DIR: "/app/testkeys/"
    volumes:
      - battery-data:/app/data
      - ./blockchain/internal/api/web/testkeys/:/app/testkeys/

  cloud-streamlit-ui:
    restart: unless-stopped
    networks: [net-iam]
    build:
      context: ./cloud/
      dockerfile: ./build/Dockerfile-ui
    working_dir: /app
    ports:
      - "8501:8501"
    environment:
      API_BASE_URL: "http://cloud-api-service:8000"
      STREAMLIT_BASE_URL: "http://localhost:8501"
    depends_on:
      - cloud-api-service

networks:
  net-iam:
    driver: bridge

volumes:
  battery-data: