services:
  nginx-dev:
    restart: unless-stopped
    stop_signal: SIGKILL
    networks: [net-blockchain]
    ports:
      - "127.0.0.1:8443:80"
    volumes:
      - ./build/nginx/blockchain-dev.conf:/etc/nginx/conf.d/default.conf:ro
    image: nginx:latest

  blockchain-api-dev:
    build:
      dockerfile: ./build/dockerfiles/blockchain-api-dev.Dockerfile
    restart: unless-stopped
    networks: [net-blockchain]
    volumes:
      - ./:/app/

  frontend-dev:
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks: [net-blockchain]
    build:
      dockerfile: ./build/dockerfiles/frontend-dev.Dockerfile

networks:
  net-blockchain:
    driver: bridge
