= Fazit & Ausblick <fazit_und_ausblick>
== Zielerreichung & Projekterfolg
Das Projekt kann insgesamt als erfolgreich bewertet werden. Sämtliche Muss-Anforderungen, die im Rahmen des Requirements Engineering definiert wurden, konnten vollständig erfüllt werden. Darüber hinaus wurde auch ein Großteil der darüber hinausgehenden Anforderungen umgesetzt. Auf dieser Grundlage wurde eine funktionale, prototypische und integrierte Lösung entwickelt, die die dezentrale Vergabe von Berechtigungen für Batteriedaten ermöglicht. Die technische Umsetzung basiert auf Blockchain-Technologie und adressiert damit gezielt das zentrale Problem der vertrauenswürdigen, nachvollziehbaren und verteilten Zugriffssteuerung. Die Zielsetzung des Projekts wurde somit inhaltlich erreicht und die entwickelte Lösung stellt einen tragfähigen Vorschlag dar, wie eine zukünftige Infrastruktur zur Verwaltung solcher Berechtigungen aussehen könnte.

== Lessons Learned
Im Projektverlauf wurde deutlich, dass die Zusammenarbeit in einem zunächst unstrukturierten und neu zusammengesetzten Team besondere Herausforderungen mit sich bringt. Ohne vorbestehende Rollenverteilungen oder eingespielte Kommunikationsprozesse gestaltete sich die Abstimmung insbesondere in den frühen Phasen schwierig. Zusätzlich war die Möglichkeit zur teaminternen Abstimmung zeitlich stark eingeschränkt, da diese im Wesentlichen nur im Rahmen der projektbegleitenden Vorlesungstermine stattfinden konnte. Im Unterschied zu einem professionellen Arbeitsumfeld, in dem ein kontinuierlicher Austausch über die gesamte Arbeitswoche hinweg möglich ist, war die Koordination hier auf wenige, eng getaktete Gelegenheiten beschränkt. Dies führte dazu, dass insbesondere in der Schlussphase des Projekts ein erhöhter Koordinations- und Integrationsaufwand notwendig war, um die verschiedenen Komponenten zu einer funktionierenden Gesamtlösung zusammenzuführen.

Darüber hinaus zeigte sich, dass die fehlende Teamstruktur zu Beginn eine zusätzliche Hürde darstellte. Da kein vordefiniertes Team existierte, mussten sich die Mitglieder zunächst selbstständig finden, ihre Zusammenarbeit aufbauen und individuelle Stärken erkennen und einbringen. Dabei wurde deutlich, wie wichtig es ist, frühzeitig klare Rollen zu definieren und die Kommunikationswege verbindlich zu gestalten. Die Notwendigkeit, grundlegende Fragen zur Arbeitsweise, zum Zeitmanagement und zur internen Abstimmung erst im laufenden Prozess klären zu müssen, führte zu Verzögerungen und wiederholten Abstimmungsproblemen.

Erschwerend kam hinzu, dass das Projektthema für alle Beteiligten völliges Neuland war. Fachbegriffe wie dezentrale Identitäten oder der digitale Batteriepass waren zu Beginn kaum bekannt, was eine aufwendige Einarbeitung erforderlich machte. Die technische und regulatorische Tiefe des Themas, insbesondere mit Blick auf künftige EU-Vorgaben, machte deutlich, wie wichtig eine strukturierte Wissensaufbereitung und kontinuierliche fachliche Orientierung im Team ist. Ohne ausreichende Vorerfahrung in Bereichen wie Batteriesysteme oder Blockchain war es zudem schwierig, den Aufwand einzelner Aufgaben realistisch einzuschätzen oder zuverlässige Zeitpläne zu entwickeln.

Ein weiteres zentrales Lernfeld bestand in der Abhängigkeit vieler Teilaufgaben voneinander. Konzepte konnten oftmals erst entwickelt oder getestet werden, wenn grundlegende Recherchen abgeschlossen oder technische Rahmenbedingungen vollständig verstanden waren. Dies machte ein hohes Maß an Flexibilität erforderlich und zeigte auf, wie stark sich Unsicherheiten im Zeitplan auf andere Arbeitsbereiche auswirken können.

Insgesamt verdeutlichte das Projekt, dass eine erfolgreiche Zusammenarbeit unter diesen Rahmenbedingungen nur durch eine klare Strukturierung, eine intensive Kommunikation und ein gemeinsames Verständnis der Projektziele möglich ist. Die Erfahrungen aus diesem Projekt unterstreichen, wie wichtig es ist, sich nicht nur mit dem fachlichen Inhalt auseinanderzusetzen, sondern auch mit der Gestaltung effizienter und transparenter Teamprozesse von Beginn an.

== Offene Punkte & Weiterentwicklung
Mit der abgeschlossenen Implementierung liegt nun eine funktionale prototypische Lösung vor, die eine dezentrale, blockchain-basierte Berechtigungsverwaltung ermöglicht. Auch wenn das Projekt mit Abgabe der Arbeit formal abgeschlossen ist, bietet die entwickelte Plattform eine tragfähige Grundlage für weitere Weiterentwicklungen. Sie wurde zur freien Weiterverwendung und gegebenenfalls kommerziellen Nutzung offengelegt. Für eine produktive Nutzung im industriellen Maßstab wären jedoch noch weitere Schritte notwendig, insbesondere im Hinblick auf Skalierung, Sicherheit und Schnittstellenstandardisierung. Dennoch leistet das Projekt einen wertvollen Beitrag zur Diskussion über zukünftige Lösungen im Bereich digitaler Berechtigungsverwaltung und liefert einen konkreten technischen Vorschlag, der als Ausgangspunkt für weiterführende Arbeiten dienen kann.
