= Fazit & Ausblick
== Zielerreichung & Projekterfolg
Das Projekt kann insgesamt als erfolgreich bewertet werden. Sämtliche Muss-Anforderungen, die im Rahmen des Requirements Engineering definiert wurden, konnten vollständig erfüllt werden. Darüber hinaus wurde auch ein Großteil der darüber hinausgehenden Anforderungen umgesetzt. Auf dieser Grundlage wurde eine funktionale, prototypische und integrierte Lösung entwickelt, die die dezentrale Vergabe von Berechtigungen für Batteriedaten ermöglicht. Die technische Umsetzung basiert auf Blockchain-Technologie und adressiert damit gezielt das zentrale Problem der vertrauenswürdigen, nachvollziehbaren und verteilten Zugriffssteuerung. Die Zielsetzung des Projekts wurde somit inhaltlich erreicht und die entwickelte Lösung stellt einen tragfähigen Vorschlag dar, wie eine zukünftige Infrastruktur zur Verwaltung solcher Berechtigungen aussehen könnte.

== Lessons Learned
Im Projektverlauf wurde deutlich, dass die Zusammenarbeit in einem zunächst unstrukturierten und neu zusammengesetzten Team besondere Herausforderungen mit sich bringt. Ohne vorbestehende Rollenverteilungen oder eingespielte Kommunikationsprozesse gestaltete sich die Abstimmung insbesondere in den frühen Phasen schwierig. Zusätzlich war die Möglichkeit zur teaminternen Abstimmung zeitlich stark eingeschränkt, da diese im Wesentlichen nur im Rahmen der projektbegleitenden Vorlesungstermine stattfinden konnte. Im Unterschied zu einem professionellen Arbeitsumfeld, in dem ein kontinuierlicher Austausch über die gesamte Arbeitswoche hinweg möglich ist, war die Koordination hier auf wenige, eng getaktete Gelegenheiten beschränkt. Dies führte dazu, dass insbesondere in der Schlussphase des Projekts ein erhöhter Koordinations- und Integrationsaufwand notwendig war, um die verschiedenen Komponenten zu einer funktionierenden Gesamtlösung zusammenzuführen. Insgesamt zeigte sich, wie wichtig es ist, bereits frühzeitig klare Strukturen, transparente Kommunikationswege und verbindliche Arbeitsprozesse zu etablieren.

== Offene Punkte & Weiterentwicklung
Mit der abgeschlossenen Implementierung liegt nun eine funktionale prototypische Lösung vor, die eine dezentrale, blockchain-basierte Berechtigungsverwaltung ermöglicht. Auch wenn das Projekt mit Abgabe der Arbeit formal abgeschlossen ist, bietet die entwickelte Plattform eine tragfähige Grundlage für weitere Weiterentwicklungen. Sie wurde zur freien Weiterverwendung und gegebenenfalls kommerziellen Nutzung offengelegt. Für eine produktive Nutzung im industriellen Maßstab wären jedoch noch weitere Schritte notwendig, insbesondere im Hinblick auf Skalierung, Sicherheit und Schnittstellenstandardisierung. Dennoch leistet das Projekt einen wertvollen Beitrag zur Diskussion über zukünftige Lösungen im Bereich digitaler Berechtigungsverwaltung und liefert einen konkreten technischen Vorschlag, der als Ausgangspunkt für weiterführende Arbeiten dienen kann.
