name: Build Diagrams and Report

on:
  push:
    branches:
      - main
    paths:
      - organizational/diagrams
      - organizational/report
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install D2
        run: |
          curl -fsSL https://d2lang.com/install.sh | sh -s --
          echo "$HOME/.d2/bin" >> $GITHUB_PATH

      - name: Generate diagrams from D2 files
        run: |
          mkdir -p assets
          for file in organizational/diagrams/*.d2; do
            filename=$(basename "$file" .d2)
            d2 "$file" "organizational/assets/${filename}.svg"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add organizational/assets/*.svg
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "action: update d2 diagrams"
            git push
          fi

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Compile Typst to PDF
        run: |
          typst compile "organizational/report/main.typ" "assets/report.pdf"

      - name: Upload PDF as release
        uses: softprops/action-gh-release@v2
        with: 
          name: "Typst PDF Release - ${{ github.sha }}"
          tag_name: "typst-${{ github.sha }}"
          files: assets/report.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
