name: Build Diagrams and Report

on:
  push:
    branches:
      - main
    paths:
      - organizational/diagrams/**
      - organizational/report/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install D2
        run: |
          curl -fsSL https://d2lang.com/install.sh | sh -s --
          echo "$HOME/.d2/bin" >> $GITHUB_PATH

      - name: Generate diagrams from D2 files
        run: |
          for file in organizational/diagrams/*.d2; do
            filename=$(basename "$file" .d2)
            d2 "$file" "organizational/report/assets/${filename}.svg"
          done

      - name: Setup SSH for Deploy Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.D2_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add organizational/report/assets/*.svg
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "action: update d2 diagrams"
            git push git@github.com:THI-CSI/decentralized_iam_battery_data.git HEAD:main
          fi

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Compile Typst to PDF
        run: |
          typst compile "organizational/report/main.typ" "organizational/report/assets/report.pdf"

      - name: Upload PDF as release
        uses: softprops/action-gh-release@v2
        with: 
          name: "Latest Report Version"
          tag_name: "latest"
          make_latest: true
          files: organizational/report/assets/report.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
