name: Build Typst to PDF

on:
  push:
    branches:
      - main
    paths:
      - organizational/report
      - organizational/diagrams
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Compile Typst to PDF
        run: |
          mkdir -p assets
          typst compile "organizational/report/main.typ" "assets/report.pdf"

      - name: Upload PDF as release
        uses: softprops/action-gh-release@v2
        with:
          name: "Typst PDF Release - ${{ github.sha }}"
          tag_name: "typst-${{ github.sha }}"
          files: assets/report.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
